version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  cicd-tests-and-lint:
    executor:
      name: node/default
      tag: '16.20.0' # Specify the Node.js version
    steps:
      - checkout
      - run:
          name: Install npm packages
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: CD - Deploy the service
          command: curl "https://api.render.com/deploy/srv-cggq95u4daddcg5bi3lg?key=RGWdF_OJ_JI"

workflows:
  example-workflow:
    jobs:
      - cicd-tests-and-lint
