name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.0'

      - name: Install npm packages
        run: npm install

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Chromedriver
        run: |
          sudo apt-get install -y unzip
          wget -N https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Download Selenium Server
        run: |
          wget https://selenium-release.storage.googleapis.com/4.21/selenium-server-4.21.0.jar -O selenium-server-4.21.0.jar

      - name: Start Selenium Grid Hub
        run: java -jar selenium-server-4.21.0.jar hub &
      
      - name: Wait for Selenium Grid Hub to start
        run: sleep 15

      - name: Start Selenium Grid Node for Chrome
        run: java -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -jar selenium-server-4.21.0.jar node --detect-drivers true --max-sessions 5 --hub http://localhost:4444 &
      
      - name: Wait for Selenium Grid Nodes to register
        run: sleep 15

      - name: Run tests
        run: npm run test

      - name: Run linter
        run: npm run lint

      - name: CD - Deploy the service
        run: curl "https://api.render.com/deploy/srv-cggq95u4daddcg5bi3lg?key=RGWdF_OJ_JI"
