name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.0'

      - name: Install npm packages
        run: npm install

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          # Set to an appropriate version, or omit to match Chrome's version automatically
          chromedriver-version: '114.0.5735.90'

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Download Selenium Server
        run: |
          wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.21.0/selenium-server-4.21.0.jar -O selenium-server-4.21.0.jar

      - name: Start Selenium Grid Hub
        run: java -jar selenium-server-4.21.0.jar hub &
      
      - name: Wait for Selenium Grid Hub to start
        run: sleep 15

      - name: Start Selenium Grid Node for Chrome
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          java -Dwebdriver.chrome.driver=$(which chromedriver) -jar selenium-server-4.21.0.jar node --detect-drivers true --max-sessions 5 --hub http://localhost:4444 &
      
      - name: Wait for Selenium Grid Nodes to register
        run: sleep 15

      - name: Run tests
        run: npm run test

      - name: Run linter
        run: npm run lint

      - name: CD - Deploy the service
        run: curl "https://api.render.com/deploy/srv-cggq95u4daddcg5bi3lg?key=RGWdF_OJ_JI"
